baseURL = "/"
locale = "en-IN"
title = "योगी सरकार की उपलब्धियां | UP Achievements"
publishDir = "docs"

[params]
  description = "10 years of Uttar Pradesh's transformation under CM Yogi Adityanath (2016–2026)"
  streamlitURL = "https://achievement-4fgbh6pguqupoqpfddsnym.streamlit.app/?embed=true"
